SELECT COUNT(*) AS row_count, COUNT(DISTINCT STORE_ACCOUNT_ID) AS distinct_opps FROM (
WITH __f AS (
select 
MERCHANT_CLOSE_DATE,
WEEK_OF,
CW_WEEK,
QTR,
YR,
QTR_YR,
READINESS_CHECK_COMPLETE_DATE,
MERCHANT_ACTIVATION_DATE,
MX_ONBOARDING_LINK_SENT_DATE,
OPPORTUNITY_ID,
STORE_ACCOUNT_ID,
BUSINESS_ACCOUNT_ID,
LEAD_ID,
WORK_ORDER_ID,
WORK_ORDER_NUMBER,
STORE_ID,
BUSINESS_ID,
PROVISIONING_STATUS,
SALES_OWNER_ID,
SALES_OWNER,
FULL_NAME,
MANAGER_NAME,
REP_ROLE,
OWNER_TEAM,
OWNER_ORG_FOCUS,
REP_SEGMENT,
SDR_OWNER,
SDR_ID,
SDR_MANAGER_ID,
SDR_MANAGER_NAME,
SDR_ROLE,
SDR_COUNTRY,
REP_COUNTRY,
CW_COUNTRY,
CLEAN_COUNTRY,
OWNER_ROLE_OFFICIAL_TITLE,
CW_OWNER_ROLE_OFFICIAL_TITLE,
SFDC_COMMISSION,
DASHPASS_COMMISSION,
NARR,
OPPORTUNITY_NAME,
OPP_TYPE,
ACCOUNT_NAME,
STORE_NAME,
BUSINESS_NAME,
DECK_RANK,
PRIMARY_VERTICAL,
COUNTRY,
STARTING_POINT_ID,
STARTING_POINT,
SUBMARKET,
SUBMARKET_ID,
TOP_MX,
MARKET_MAKER,
IS_GNC,
IS_DASHPASS,
IS_PICKUP,
IS_STOREFRONT,
IS_ALCOHOL,
IS_TRIAL,
IS_PROMO,
IS_ADS,
IS_ADS_PROMOS,
PACKAGE_SOLD,
NTAM,
INCREMENTAL_SIGN_TAM,
HISTORICAL_DELAY_REASONS_CUSTOMIZED,
LEAD_LIST_CUSTOMIZED,
TRIAL_PERIOD,
TOP_MX_SIGNING_BONUS_APPROVAL_THRESHOLD,
ACTIVATION_BONUS_AMOUNT,
PRODUCT_LIST,
REGION,
TIER,
SFDC_SOURCE,
LAST_ETL_RUN
from REDACTED_DB.static.presales_cw_level
),
__s0 AS (
  SELECT
    "ROLE_ACTIVATIONS" AS "ROLE_ACTIVATIONS",
    "COUNTRY" AS "COUNTRY",
    MAX("WEEK_GOAL_ACTIVATIONS") AS "WEEK_GOAL_ACTIVATIONS",
    SUM("ACTIVATION_GOAL") AS "ACTIVATION_GOAL",
    MAX("QUARTER_YEAR") AS "QUARTER_YEAR"
  FROM (
SELECT *
FROM REDACTED_DB.static.activations_goals_presales "ACTIVATIONS_GOALS_PRESALES"
) "__src_0"
  GROUP BY "ROLE_ACTIVATIONS", "COUNTRY"
),
__s1 AS (
  SELECT
    "OWNER_ROLE_OFFICIAL_TITLE (PRESALES_ACTIVE_HC)" AS "OWNER_ROLE_OFFICIAL_TITLE (PRESALES_ACTIVE_HC)",
    "QTR_YR (PRESALES_ACTIVE_HC)" AS "QTR_YR (PRESALES_ACTIVE_HC)",
    MAX("COUNTRY (PRESALES_ACTIVE_HC)") AS "COUNTRY (PRESALES_ACTIVE_HC)",
    SUM("DAYS_OFF") AS "DAYS_OFF",
    SUM("HC") AS "HC",
    MAX("QTR (PRESALES_ACTIVE_HC)") AS "QTR (PRESALES_ACTIVE_HC)",
    MAX("REP_RANK") AS "REP_RANK",
    MAX("SALES_MANAGER") AS "SALES_MANAGER",
    MAX("SALES_OWNER (PRESALES_ACTIVE_HC)") AS "SALES_OWNER (PRESALES_ACTIVE_HC)",
    MAX("USER_ID") AS "USER_ID",
    MAX("WEEK_OF (PRESALES_ACTIVE_HC)") AS "WEEK_OF (PRESALES_ACTIVE_HC)",
    SUM("YR (PRESALES_ACTIVE_HC)") AS "YR (PRESALES_ACTIVE_HC)"
  FROM (
with final as (
select 
    case 
        when rep_segment = 'CAN SMB Sales' then 'Canada' 
        when rep_segment not in ('AUS SMB Sales','CAN SMB Sales','NZ SMB Sales','ANZ SMB Sales') then 'United States' 
        else null 
    end as country, 
    days_off,
    days_worked/iff(working_days=0,null,working_days) as hc,
    role_title as OWNER_ROLE_OFFICIAL_TITLE,
    'Q'||quarter(to_date(week)) as qtr,
        year(to_date(week)) as yr,
        qtr||'-'||right(yr,2) as qtr_yr,
    null as rep_rank,
    null as SALES_MANAGER,
    rep_name as sales_owner,
    ddmx_id as user_id,
    week as week_of
from REDACTED_DB.public.sales_analytics_bis
where country is not null
)
SELECT "PRESALES_ACTIVE_HC"."COUNTRY" AS "COUNTRY (PRESALES_ACTIVE_HC)",
  "PRESALES_ACTIVE_HC"."DAYS_OFF" AS "DAYS_OFF",
  "PRESALES_ACTIVE_HC"."HC" AS "HC",
  "PRESALES_ACTIVE_HC"."OWNER_ROLE_OFFICIAL_TITLE" AS "OWNER_ROLE_OFFICIAL_TITLE (PRESALES_ACTIVE_HC)",
  "PRESALES_ACTIVE_HC"."QTR" AS "QTR (PRESALES_ACTIVE_HC)",
  "PRESALES_ACTIVE_HC"."QTR_YR" AS "QTR_YR (PRESALES_ACTIVE_HC)",
  "PRESALES_ACTIVE_HC"."REP_RANK" AS "REP_RANK",
  "PRESALES_ACTIVE_HC"."SALES_MANAGER" AS "SALES_MANAGER",
  "PRESALES_ACTIVE_HC"."SALES_OWNER" AS "SALES_OWNER (PRESALES_ACTIVE_HC)",
  "PRESALES_ACTIVE_HC"."USER_ID" AS "USER_ID",
  "PRESALES_ACTIVE_HC"."WEEK_OF" AS "WEEK_OF (PRESALES_ACTIVE_HC)",
  "PRESALES_ACTIVE_HC"."YR" AS "YR (PRESALES_ACTIVE_HC)"
FROM final "PRESALES_ACTIVE_HC"
) "__src_1"
  GROUP BY "OWNER_ROLE_OFFICIAL_TITLE (PRESALES_ACTIVE_HC)", "QTR_YR (PRESALES_ACTIVE_HC)"
),
__s2 AS (
  SELECT
    "WEEK_GOAL" AS "WEEK_GOAL",
    "ROLE (PRESALE_PRODUCT_GOALS)" AS "ROLE (PRESALE_PRODUCT_GOALS)",
    MAX("BASED") AS "BASED",
    MAX("ORG") AS "ORG",
    MAX("PRODUCT") AS "PRODUCT",
    SUM("PRODUCT_GOAL") AS "PRODUCT_GOAL",
    MAX("QTR_YR_PG") AS "QTR_YR_PG",
    MAX("TARGET") AS "TARGET",
    MAX("TEAM") AS "TEAM"
  FROM (
SELECT "PRESALE_PRODUCT_GOALS"."BASED" AS "BASED",
  "PRESALE_PRODUCT_GOALS"."ORG" AS "ORG",
  "PRESALE_PRODUCT_GOALS"."PRODUCT" AS "PRODUCT",
  "PRESALE_PRODUCT_GOALS"."PRODUCT_GOAL" AS "PRODUCT_GOAL",
  "PRESALE_PRODUCT_GOALS"."QTR_YR_PG" AS "QTR_YR_PG",
  "PRESALE_PRODUCT_GOALS"."ROLE" AS "ROLE (PRESALE_PRODUCT_GOALS)",
  "PRESALE_PRODUCT_GOALS"."TARGET" AS "TARGET",
  "PRESALE_PRODUCT_GOALS"."TEAM" AS "TEAM",
  (CASE WHEN (NOT (CAST(TO_TIMESTAMP("PRESALE_PRODUCT_GOALS"."WEEK_GOAL", 'MM/DD/YYYY') AS DATE) IS NULL)) THEN CAST(TO_TIMESTAMP("PRESALE_PRODUCT_GOALS"."WEEK_GOAL", 'MM/DD/YYYY') AS DATE) WHEN (NOT (TRY_CAST("PRESALE_PRODUCT_GOALS"."WEEK_GOAL" AS DATE) IS NULL)) THEN TRY_CAST("PRESALE_PRODUCT_GOALS"."WEEK_GOAL" AS DATE) ELSE NULL END) AS "WEEK_GOAL"
FROM REDACTED_DB."STATIC"."PRESALE_PRODUCT_GOALS" "PRESALE_PRODUCT_GOALS"
) "__src_2"
  GROUP BY "WEEK_GOAL", "ROLE (PRESALE_PRODUCT_GOALS)"
),
__s3 AS (
  SELECT
    "ROLE_SP" AS "ROLE_SP",
    MAX("WEEK_GOAL_SP") AS "WEEK_GOAL_SP",
    MAX("INITIATIVE") AS "INITIATIVE",
    SUM("INITIATIVE_GOAL") AS "INITIATIVE_GOAL",
    MAX("QTR_YR_SP") AS "QTR_YR_SP"
  FROM (
SELECT *
FROM REDACTED_DB.static.presale_special_projects_goals
) "__src_3"
  GROUP BY "ROLE_SP"
),
__s4 AS (
  SELECT
    "CW_WEEK" AS "CW_WEEK",
    "ROLE" AS "ROLE",
    "QTR_YR" AS "QTR_YR",
    "COUNTRY" AS "COUNTRY",
    MAX("QTR") AS "QTR",
    SUM("YR") AS "YR",
    SUM("CLOSES") AS "CLOSES",
    SUM("NARR") AS "NARR",
    SUM("WORKING_DAYS") AS "WORKING_DAYS",
    SUM("AHC_GOAL") AS "AHC_GOAL",
    SUM("CLOSE_PHASING") AS "CLOSE_PHASING",
    MAX("WEEK_OF") AS "WEEK_OF"
  FROM (
select * from REDACTED_DB.static.presale_weekly_goals
) "__src_4"
  GROUP BY "CW_WEEK", "ROLE", "QTR_YR", "COUNTRY"
),
__s5 AS (
  SELECT
    "ROLE_SP" AS "ROLE_SP",
    MAX("WEEK_GOAL_SP") AS "WEEK_GOAL_SP",
    MAX("INITIATIVE") AS "INITIATIVE",
    SUM("INITIATIVE_GOAL") AS "INITIATIVE_GOAL",
    MAX("QTR_YR_SP") AS "QTR_YR_SP"
  FROM (
select * from REDACTED_DB.static.presale_special_projects_goals
) "__src_5"
  GROUP BY "ROLE_SP"
),
__s6 AS (
  SELECT
    "ROLE_SP" AS "ROLE_SP",
    MAX("WEEK_GOAL_SP") AS "WEEK_GOAL_SP",
    MAX("INITIATIVE") AS "INITIATIVE",
    SUM("INITIATIVE_GOAL") AS "INITIATIVE_GOAL",
    MAX("QTR_YR_SP") AS "QTR_YR_SP"
  FROM (
select * from REDACTED_DB.static.presale_special_projects_goals
) "__src_6"
  GROUP BY "ROLE_SP"
)
SELECT
  __f."MERCHANT_CLOSE_DATE" AS "MERCHANT_CLOSE_DATE",
  __f."WEEK_OF" AS "WEEK_OF",
  __f."CW_WEEK" AS "CW_WEEK",
  __f."QTR" AS "QTR",
  __f."YR" AS "YR",
  __f."QTR_YR" AS "QTR_YR",
  __f."READINESS_CHECK_COMPLETE_DATE" AS "READINESS_CHECK_COMPLETE_DATE",
  __f."MERCHANT_ACTIVATION_DATE" AS "MERCHANT_ACTIVATION_DATE",
  __f."MX_ONBOARDING_LINK_SENT_DATE" AS "MX_ONBOARDING_LINK_SENT_DATE",
  __f."OPPORTUNITY_ID" AS "OPPORTUNITY_ID",
  __f."STORE_ACCOUNT_ID" AS "STORE_ACCOUNT_ID",
  __f."BUSINESS_ACCOUNT_ID" AS "BUSINESS_ACCOUNT_ID",
  __f."LEAD_ID" AS "LEAD_ID",
  __f."WORK_ORDER_ID" AS "WORK_ORDER_ID",
  __f."WORK_ORDER_NUMBER" AS "WORK_ORDER_NUMBER",
  __f."STORE_ID" AS "STORE_ID",
  __f."BUSINESS_ID" AS "BUSINESS_ID",
  __f."PROVISIONING_STATUS" AS "PROVISIONING_STATUS",
  __f."SALES_OWNER_ID" AS "SALES_OWNER_ID",
  __f."SALES_OWNER" AS "SALES_OWNER",
  __f."FULL_NAME" AS "FULL_NAME",
  __f."MANAGER_NAME" AS "MANAGER_NAME",
  __f."REP_ROLE" AS "REP_ROLE",
  __f."OWNER_TEAM" AS "OWNER_TEAM",
  __f."OWNER_ORG_FOCUS" AS "OWNER_ORG_FOCUS",
  __f."REP_SEGMENT" AS "REP_SEGMENT",
  __f."SDR_OWNER" AS "SDR_OWNER",
  __f."SDR_ID" AS "SDR_ID",
  __f."SDR_MANAGER_ID" AS "SDR_MANAGER_ID",
  __f."SDR_MANAGER_NAME" AS "SDR_MANAGER_NAME",
  __f."SDR_ROLE" AS "SDR_ROLE",
  __f."SDR_COUNTRY" AS "SDR_COUNTRY",
  __f."REP_COUNTRY" AS "REP_COUNTRY",
  __f."CW_COUNTRY" AS "CW_COUNTRY",
  __f."CLEAN_COUNTRY" AS "CLEAN_COUNTRY",
  __f."OWNER_ROLE_OFFICIAL_TITLE" AS "OWNER_ROLE_OFFICIAL_TITLE",
  __f."CW_OWNER_ROLE_OFFICIAL_TITLE" AS "CW_OWNER_ROLE_OFFICIAL_TITLE",
  __f."SFDC_COMMISSION" AS "SFDC_COMMISSION",
  __f."DASHPASS_COMMISSION" AS "DASHPASS_COMMISSION",
  __f."NARR" AS "NARR",
  __f."OPPORTUNITY_NAME" AS "OPPORTUNITY_NAME",
  __f."OPP_TYPE" AS "OPP_TYPE",
  __f."ACCOUNT_NAME" AS "ACCOUNT_NAME",
  __f."STORE_NAME" AS "STORE_NAME",
  __f."BUSINESS_NAME" AS "BUSINESS_NAME",
  __f."DECK_RANK" AS "DECK_RANK",
  __f."PRIMARY_VERTICAL" AS "PRIMARY_VERTICAL",
  __f."COUNTRY" AS "COUNTRY",
  __f."STARTING_POINT_ID" AS "STARTING_POINT_ID",
  __f."STARTING_POINT" AS "STARTING_POINT",
  __f."SUBMARKET" AS "SUBMARKET",
  __f."SUBMARKET_ID" AS "SUBMARKET_ID",
  __f."TOP_MX" AS "TOP_MX",
  __f."MARKET_MAKER" AS "MARKET_MAKER",
  __f."IS_GNC" AS "IS_GNC",
  __f."IS_DASHPASS" AS "IS_DASHPASS",
  __f."IS_PICKUP" AS "IS_PICKUP",
  __f."IS_STOREFRONT" AS "IS_STOREFRONT",
  __f."IS_ALCOHOL" AS "IS_ALCOHOL",
  __f."IS_TRIAL" AS "IS_TRIAL",
  __f."IS_PROMO" AS "IS_PROMO",
  __f."IS_ADS" AS "IS_ADS",
  __f."IS_ADS_PROMOS" AS "IS_ADS_PROMOS",
  __f."PACKAGE_SOLD" AS "PACKAGE_SOLD",
  __f."NTAM" AS "NTAM",
  __f."INCREMENTAL_SIGN_TAM" AS "INCREMENTAL_SIGN_TAM",
  __f."HISTORICAL_DELAY_REASONS_CUSTOMIZED" AS "HISTORICAL_DELAY_REASONS_CUSTOMIZED",
  __f."LEAD_LIST_CUSTOMIZED" AS "LEAD_LIST_CUSTOMIZED",
  __f."TRIAL_PERIOD" AS "TRIAL_PERIOD",
  __f."TOP_MX_SIGNING_BONUS_APPROVAL_THRESHOLD" AS "TOP_MX_SIGNING_BONUS_APPROVAL_THRESHOLD",
  __f."ACTIVATION_BONUS_AMOUNT" AS "ACTIVATION_BONUS_AMOUNT",
  __f."PRODUCT_LIST" AS "PRODUCT_LIST",
  __f."REGION" AS "REGION",
  __f."TIER" AS "TIER",
  __f."SFDC_SOURCE" AS "SFDC_SOURCE",
  __f."LAST_ETL_RUN" AS "LAST_ETL_RUN",
  __s0."WEEK_GOAL_ACTIVATIONS" AS "WEEK_GOAL_ACTIVATIONS",
  __s0."ROLE_ACTIVATIONS" AS "ROLE_ACTIVATIONS",
  __s0."ACTIVATION_GOAL" AS "ACTIVATION_GOAL",
  __s0."QUARTER_YEAR" AS "QUARTER_YEAR",
  __s0."COUNTRY" AS "COUNTRY_2",
  __s1."COUNTRY (PRESALES_ACTIVE_HC)" AS "COUNTRY_3",
  __s1."DAYS_OFF" AS "DAYS_OFF",
  __s1."HC" AS "HC",
  __s1."OWNER_ROLE_OFFICIAL_TITLE (PRESALES_ACTIVE_HC)" AS "OWNER_ROLE_OFFICIAL_TITLE_2",
  __s1."QTR (PRESALES_ACTIVE_HC)" AS "QTR_2",
  __s1."QTR_YR (PRESALES_ACTIVE_HC)" AS "QTR_YR_2",
  __s1."REP_RANK" AS "REP_RANK",
  __s1."SALES_MANAGER" AS "SALES_MANAGER",
  __s1."SALES_OWNER (PRESALES_ACTIVE_HC)" AS "SALES_OWNER_2",
  __s1."USER_ID" AS "USER_ID",
  __s1."WEEK_OF (PRESALES_ACTIVE_HC)" AS "WEEK_OF_2",
  __s1."YR (PRESALES_ACTIVE_HC)" AS "YR_2",
  __s2."BASED" AS "BASED",
  __s2."ORG" AS "ORG",
  __s2."PRODUCT" AS "PRODUCT",
  __s2."PRODUCT_GOAL" AS "PRODUCT_GOAL",
  __s2."QTR_YR_PG" AS "QTR_YR_PG",
  __s2."ROLE (PRESALE_PRODUCT_GOALS)" AS "ROLE",
  __s2."TARGET" AS "TARGET",
  __s2."TEAM" AS "TEAM",
  __s2."WEEK_GOAL" AS "WEEK_GOAL",
  __s3."WEEK_GOAL_SP" AS "WEEK_GOAL_SP",
  __s3."INITIATIVE" AS "INITIATIVE",
  __s3."INITIATIVE_GOAL" AS "INITIATIVE_GOAL",
  __s3."QTR_YR_SP" AS "QTR_YR_SP",
  __s3."ROLE_SP" AS "ROLE_SP",
  __s4."QTR" AS "QTR_3",
  __s4."YR" AS "YR_3",
  __s4."QTR_YR" AS "QTR_YR_3",
  __s4."COUNTRY" AS "COUNTRY_4",
  __s4."ROLE" AS "ROLE_2",
  __s4."CLOSES" AS "CLOSES",
  __s4."NARR" AS "NARR_2",
  __s4."CW_WEEK" AS "CW_WEEK_2",
  __s4."WORKING_DAYS" AS "WORKING_DAYS",
  __s4."AHC_GOAL" AS "AHC_GOAL",
  __s4."CLOSE_PHASING" AS "CLOSE_PHASING",
  __s4."WEEK_OF" AS "WEEK_OF_3",
  __s5."WEEK_GOAL_SP" AS "WEEK_GOAL_SP_2",
  __s5."INITIATIVE" AS "INITIATIVE_2",
  __s5."INITIATIVE_GOAL" AS "INITIATIVE_GOAL_2",
  __s5."QTR_YR_SP" AS "QTR_YR_SP_2",
  __s5."ROLE_SP" AS "ROLE_SP_2",
  __s6."WEEK_GOAL_SP" AS "WEEK_GOAL_SP_3",
  __s6."INITIATIVE" AS "INITIATIVE_3",
  __s6."INITIATIVE_GOAL" AS "INITIATIVE_GOAL_3",
  __s6."QTR_YR_SP" AS "QTR_YR_SP_3",
  __s6."ROLE_SP" AS "ROLE_SP_3"
FROM __f
LEFT JOIN __s0 ON __f."CW_OWNER_ROLE_OFFICIAL_TITLE" = __s0."ROLE_ACTIVATIONS" AND __f."CW_COUNTRY" = __s0."COUNTRY"
LEFT JOIN __s1 ON __f."CW_OWNER_ROLE_OFFICIAL_TITLE" = __s1."OWNER_ROLE_OFFICIAL_TITLE (PRESALES_ACTIVE_HC)" AND __f."QTR_YR" = __s1."QTR_YR (PRESALES_ACTIVE_HC)"
LEFT JOIN __s2 ON __f."WEEK_OF" = __s2."WEEK_GOAL" AND __f."CW_OWNER_ROLE_OFFICIAL_TITLE" = __s2."ROLE (PRESALE_PRODUCT_GOALS)"
LEFT JOIN __s3 ON __f."CW_OWNER_ROLE_OFFICIAL_TITLE" = __s3."ROLE_SP"
LEFT JOIN __s4 ON __f."CW_WEEK" = __s4."CW_WEEK" AND __f."CW_OWNER_ROLE_OFFICIAL_TITLE" = __s4."ROLE" AND __f."QTR_YR" = __s4."QTR_YR" AND __f."CW_COUNTRY" = __s4."COUNTRY"
LEFT JOIN __s5 ON __f."CW_OWNER_ROLE_OFFICIAL_TITLE" = __s5."ROLE_SP"
LEFT JOIN __s6 ON __f."CW_OWNER_ROLE_OFFICIAL_TITLE" = __s6."ROLE_SP"
) q;